/*
 * This file is generated by jOOQ.
 */
package com.pastefile.domain.db;


import com.pastefile.domain.db.tables.Files;
import com.pastefile.domain.db.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
